#!/usr/bin/env python3
"""
Security Code Generator and Email Sender
Generates a random 3-digit binary code and sends it to admin via email
"""

import random
import smtplib
import json
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# --- Configuration ---
# Your email address (must be a valid sender account)
SENDER_EMAIL = "sohamghoshchoudhury25@gmail.com"
# The App Password generated by your email provider
SENDER_PASSWORD = "yrwd nblf bhij hmsr"
# The admin's email address
RECIPIENT_EMAIL = "thewriterranjan@gmail.com"
# SMTP server details (Example for Gmail)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587  # 587 for TLS, 465 for SSL

def generate_security_code():
    """Generates a string of three random binary digits (0 or 1)."""
    # Generate 3 random choices (0 or 1) and join them into a string
    code = [str(random.randint(0, 1)) for _ in range(3)]
    return " ".join(code)

def send_admin_email(code):
    """Sends the generated security code to the admin via email."""
    
    # 1. Create the email content
    subject = "Threat Security Code Alert"
    body = f"""
***ADMIN URGENT SECURITY ALERT***

Dear Administrator,

The following is the current **Vulnerability Response Code** generated by the system. This unique token is to be used *only* during an active security threat or system breach event as per protocol.

**RESPONSE CODE:** {code}

**Action Required:**
1. Securely log this code.
2. Refer to the Emergency Response Manual for proper use during an incident.

Do not use this code for routine operations.

Security System Automation - VectorVault
"""
    
    message = MIMEMultipart()
    message["From"] = SENDER_EMAIL
    message["To"] = RECIPIENT_EMAIL
    message["Subject"] = subject
    
    # Attach the body to the email
    message.attach(MIMEText(body, 'plain'))
    
    try:
        # 2. Connect to the SMTP server and send the email
        # Use a context manager (with smtplib.SMTP) for automatic connection handling
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            # Start TLS encryption for security
            server.starttls()
            
            # Log in to your email account
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            
            # Send the email
            server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, message.as_string())
            
        return True, f"Successfully sent email to {RECIPIENT_EMAIL}"
        
    except Exception as e:
        return False, f"Failed to send email. Error: {str(e)}"

# --- Main execution ---
if __name__ == "__main__":
    try:
        # 1. Generate the code
        security_code = generate_security_code()
        
        # 2. Send the email
        success, message = send_admin_email(security_code)
        
        # 3. Return JSON response for Node.js integration
        result = {
            "success": success,
            "code": security_code,
            "message": message,
            "recipient": RECIPIENT_EMAIL
        }
        
        print(json.dumps(result))
        sys.exit(0 if success else 1)
        
    except Exception as e:
        error_result = {
            "success": False,
            "error": str(e),
            "message": "Failed to generate or send security code"
        }
        print(json.dumps(error_result))
        sys.exit(1)
